project:
  type: website
  output-dir: docs

website:
  favicon: "assets/favicon.ico"
  title: "JuliaHealth"
  image: "assets/images/logo.png"
  image-alt: "JuliaHub Logo"
  navbar:
    logo: "assets/images/logo.png"
    logo-alt: "JuliaHub Logo"
    left:
      - href: index.qmd
        text: Home
        icon: house-door
      - href: pages/packages.qmd
        text: Packages
        icon: boxes
      - href: JuliaHealthBlog/index.qmd
        text: Blogs
        icon: journal-richtext
      - href: pages/connect_with_us.qmd
        text: Connect With Us
        icon: chat-heart
      - text: "More"
        menu:
          - href: pages/meeting_notes.qmd
            text: Meetings Notes
            icon: card-text
          - href: pages/related_organizations.qmd
            text: Related Organizations
            icon: buildings
  page-footer:
    left:
      - text: "Copyright 2024-25, JuliaHealth."
        icon: c-circle
    right:
      - href: https://github.com/JuliaHealth/JuliaHealthBlog
        text: Report Issue

bread-crumbs: true

format:
  html:
    theme:
      light: 
        - cosmo
        - brand
    css: styles.css
    toc: true
