project:
  type: website
  output-dir: docs

website:
  favicon: "assets/favicon.ico"
  title: "JuliaHealth"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog/index.qmd
        text: Blogs
      - href: pages/connect_with_us.qmd
        text: Connect With Us
        icon: chat-heart
      - text: "More"
        menu:
          - href: pages/meeting_notes.qmd
            text: Meetings Notes
          - href: pages/related_organizations.qmd
            text: Related Organizations
  page-footer:
    left: "Copyright 2024-25, JuliaHealth."
    right:
      - href: https://github.com/JuliaHealth/JuliaHealthBlog
        text: Report Issue

bread-crumbs: true

format:
  html:
    theme:
      light: 
        - cosmo
        - brand
    css: styles.css
    toc: true
